### ISSUE TITLE
Rename to accessiblity reviews?

### ISSUE THREAD

**Issue by NickColley** [a11y-reviews/a11y.reviews#11]
If we want to reach the most people could we consider using 'accessibility' rather than a11y?

**Comment by aardrian** [comment]
That is the name in the `<title>` and the `<h1>`. The project name reflects the domain name. Are you talking about somewhere else? Something I missed?

**Comment by NickColley** [comment]
Fair I guess if it's only used for the domain name it's not likely to exclude people
