### ISSUE TITLE
Ongoing review of Hashnode

### ISSUE THREAD

**Issue by AutoSponge** [a11y-reviews/a11y.reviews#20]
I'm working on a review of Hashnode's developer content platform. [First post here](https://ytho.dev/hashnode-ytho-ck7xdp9sq02ejzns1ydc4m3m8). Would you rather I add it when I'm completely done?

**Comment by aardrian** [comment]
Dunno how I missed this. Oh right -- my alerts are borked.

I think you can add it and amend as you learn more. Better to get good info in front of folks sooner rather than later.
